@startuml

title __CONTACTS's Component Diagram__\n

  component "Contacts.util.main" {
        [Contacts.util]
  }


  component "Contacts.Contacts-task.main" {
        [Contacts.Contacts-task]
  }


  component "Contacts.Problems-Burgers.main" {
        [Contacts.Problems-Burgers]
  }


  component "Contacts.Problems-Builder.main" {
        [Contacts.Problems-Builder]
  }


  component "Contacts.Problems-Who_is_who.main" {
        [Contacts.Problems-Who_is_who]
  }


  component "Contacts.Problems-Undo_command.main" {
        [Contacts.Problems-Undo_command]
  }


  component "Contacts.Problems-Stock_Broker.main" {
        [Contacts.Problems-Stock_Broker]
  }


  component "Contacts.Problems-Geek_Builder.main" {
        [Contacts.Problems-Geek_Builder]
  }


  component "Contacts.Problems-Forex_Broker.main" {
        [Contacts.Problems-Forex_Broker]
  }


  component "Contacts.Problems-Robot_Builder.main" {
        [Contacts.Problems-Robot_Builder]
  }


  component "Contacts.Problems-Phone_factory.main" {
        [Contacts.Problems-Phone_factory]
  }


  component "Contacts.Problems-Laptop_factory.main" {
        [Contacts.Problems-Laptop_factory]
  }


  component "Contacts.Problems-10_days_before.main" {
        [Contacts.Problems-10_days_before]
  }


  component "Contacts.Problems-Subway_Sandwich.main" {
        [Contacts.Problems-Subway_Sandwich]
  }


  component "Contacts.Problems-Sum_of_the_areas.main" {
        [Contacts.Problems-Sum_of_the_areas]
  }


  component "Contacts.Problems-Adding_N_minutes.main" {
        [Contacts.Problems-Adding_N_minutes]
  }


  component "Contacts.Problems-Remote_Controller.main" {
        [Contacts.Problems-Remote_Controller]
  }


  component "Contacts.Problems-Counting_2D_shapes.main" {
        [Contacts.Problems-Counting_2D_shapes]
  }


  component "Contacts.Problems-Sort_out_the_classes.main" {
        [Contacts.Problems-Sort_out_the_classes]
  }


  component "Contacts.Problems-30_years_before_and_after.main" {
        [Contacts.Problems-30_years_before_and_after]
  }


  component "Contacts.Problems-Merging_date-time_instances.main" {
        [Contacts.Problems-Merging_date-time_instances]
  }


  component "Contacts.Problems-The_index_of_the_K_occurrence.main" {
        [Contacts.Problems-The_index_of_the_K_occurrence]
  }


  component "Contacts.Problems-The_n-th_day_from_the_end_of_a_month.main" {
        [Contacts.Problems-The_n-th_day_from_the_end_of_a_month]
  }


  component "Contacts.Problems-The_first_and_the_last_day_of_a_month.main" {
        [Contacts.Problems-The_first_and_the_last_day_of_a_month]
  }




right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
